-- MySQL Script generated by MySQL Workbench
-- mar 05 mar 2019 17:18:20 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BrafeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BrafeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BrafeDB` DEFAULT CHARACTER SET utf8 ;
USE `BrafeDB` ;

-- -----------------------------------------------------
-- Table `BrafeDB`.`Erabiltzaileak`
-- -----------------------------------------------------
CREATE TABLE IF EXISTS `BrafeDB`.`Erabiltzaileak` (
  `ErabiltzaileakID` INT NOT NULL,
  `Izena` VARCHAR(45) NULL,
  `Abizenak` VARCHAR(45) NULL,
  `JaioteData` DATE NULL,
  `Zonaldea` VARCHAR(45) NULL,
  `AlarmaMail` VARCHAR(45) NULL,
  `Balorazioa` FLOAT NULL,
  `ErabiltzaileMota` VARCHAR(45) NULL,
  `Pasahitza` VARCHAR(45) NULL,
  `ErabiltzaileEgoera` VARCHAR(45) NULL,
  `ErabiltzaileMail` VARCHAR(50) NULL,
  PRIMARY KEY (`ErabiltzaileakID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrafeDB`.`Ekitaldiak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrafeDB`.`Ekitaldiak` (
  `EkitaldiID` INT NOT NULL,
  `EkitaldiIzena` VARCHAR(45) NULL,
  `EkitaldiData` DATE NULL,
  `Partaideak` INT(11) NULL,
  `EkitaldiSortzailea` VARCHAR(45) NULL,
  `Kokapena` VARCHAR(45) NULL,
  PRIMARY KEY (`EkitaldiID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrafeDB`.`Azpiekitaldiak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrafeDB`.`Azpiekitaldiak` (
  `AzpiekitaldiID` INT NOT NULL,
  `AzpiekitaldiPartaide` INT(11) NULL,
  `Zonaldea` VARCHAR(45) NULL,
  `AzpiekitaldiIzena` VARCHAR(45) NULL,
  `Ekitaldiak_EkitaldiID` INT NOT NULL,
  PRIMARY KEY (`AzpiekitaldiID`),
  INDEX `fk_Azpiekitaldiak_Ekitaldiak_idx` (`Ekitaldiak_EkitaldiID` ASC),
  CONSTRAINT `fk_Azpiekitaldiak_Ekitaldiak`
    FOREIGN KEY (`Ekitaldiak_EkitaldiID`)
    REFERENCES `BrafeDB`.`Ekitaldiak` (`EkitaldiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrafeDB`.`Geldialdiak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrafeDB`.`Geldialdiak` (
  `GeldialdiID` INT NOT NULL,
  `GeldialdiIzena` VARCHAR(45) NULL,
  `BatazbestekoBalorazioa` INT(11) NULL,
  `GeldialdiIraungiteData` VARCHAR(45) NULL,
  `Azpiekitaldiak_AzpiekitaldiID` INT NOT NULL,
  PRIMARY KEY (`GeldialdiID`),
  INDEX `fk_Geldialdiak_Azpiekitaldiak1_idx` (`Azpiekitaldiak_AzpiekitaldiID` ASC),
  CONSTRAINT `fk_Geldialdiak_Azpiekitaldiak1`
    FOREIGN KEY (`Azpiekitaldiak_AzpiekitaldiID`)
    REFERENCES `BrafeDB`.`Azpiekitaldiak` (`AzpiekitaldiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BrafeDB`.`Baieztatuak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BrafeDB`.`Baieztatuak` (
  `Geralekua` VARCHAR(45) NOT NULL,
  `Geldialdiak_GeldialdiID` INT NOT NULL,
  `Erabiltzaileak_ErabiltzaileakID` INT NOT NULL,
  PRIMARY KEY (`Geralekua`, `Geldialdiak_GeldialdiID`),
  INDEX `fk_Baieztatuak_Geldialdiak1_idx` (`Geldialdiak_GeldialdiID` ASC),
  INDEX `fk_Baieztatuak_Erabiltzaileak1_idx` (`Erabiltzaileak_ErabiltzaileakID` ASC),
  CONSTRAINT `fk_Baieztatuak_Geldialdiak1`
    FOREIGN KEY (`Geldialdiak_GeldialdiID`)
    REFERENCES `BrafeDB`.`Geldialdiak` (`GeldialdiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baieztatuak_Erabiltzaileak1`
    FOREIGN KEY (`Erabiltzaileak_ErabiltzaileakID`)
    REFERENCES `BrafeDB`.`Erabiltzaileak` (`ErabiltzaileakID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
